name: PhpUnit Coverage Badge

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'
          extensions:  simplexml, dom, xml, xdebug, intl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Recreate autoload file
        run: composer dump-autoload

      - name: Run Psalm
        run: composer psalm

      - name: Run PHP_CS
        run: composer phpcs

      - name: Run Unit Tests
        run: XDEBUG_MODE_COVERAGE=coverage vendor/bin/phpunit

      - name: Cache docker container
        id: cache-docker-image
        uses: actions/cache@v2
        with:
          path: ~/docker-temp/coverageBadge.tar
          key: ${{ runner.os }}-image

      - name: Load docker image
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: /usr/bin/docker load < ~/docker-temp/coverageBadge.tar

      - name: Generate test coverage badge
        uses: ./
        with:
          coverage_badge_path: 'badge.svg'
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save docker image
        run: mkdir -p ~/docker-temp/ && /usr/bin/docker save ghcr.io/timkrase/phpunit-coverage-badge > ~/docker-temp/coverageBadge.tar