name: PhpUnit Coverage Badge

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'
          extensions:  simplexml, dom, xml, xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Recreate autoload file
        run: composer dump-autoload

      - name: Run Unit Tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit

      - name: Generate test coverage badge
        uses: ./
        with:
          clover_report: 'clover.xml'
          coverage_badge_path: 'badge.svg'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          push_badge: false
